const mockPrescriptions = [
  {
    id: 'presc_001',
    patientName: 'Amit Sharma',
    type: 'image',
    fileName: 'blood_test.jpg',
    fileUri: 'https://example.com/mock-images/presc1.jpg',
    thumbnailUri: 'https://example.com/mock-images/thumbs/presc1.jpg',
    notes: 'Monthly blood test - fasting',
    uploadedBy: 'user',
    status: 'pending',
    createdAt: '2025-10-02T09:15:00.000Z',
    reminderDate: '2025-11-10T08:00:00.000Z',
  },
  {
    id: 'presc_002',
    patientName: 'Priya Verma',
    type: 'pdf',
    fileName: 'prescription_oct.pdf',
    fileUri: 'https://example.com/mock-pdfs/presc2.pdf',
    thumbnailUri: 'https://example.com/mock-images/thumbs/pdf-placeholder.png',
    notes: 'Antibiotics for 5 days',
    uploadedBy: 'clinic',
    status: 'missed',
    createdAt: '2025-09-28T12:00:00.000Z',
    reminderDate: '2025-11-05T09:00:00.000Z',
  },
  {
    id: 'presc_003',
    patientName: 'Rahul Joshi',
    type: 'link',
    fileName: 'external-prescription',
    fileUri: 'https://example-docs.example.com/raz/prescription/345',
    thumbnailUri: 'https://example.com/mock-images/thumbs/link-placeholder.png',
    notes: 'Teleconsultation link — see attached summary',
    uploadedBy: 'doctor',
    status: 'pending',
    createdAt: '2025-10-18T16:30:00.000Z',
    reminderDate: '2025-11-07T10:30:00.000Z',
  },
  {
    id: 'presc_004',
    patientName: 'Sneha Gupta',
    type: 'image',
    fileName: 'skin_allergy.png',
    fileUri: 'https://example.com/mock-images/presc4.png',
    thumbnailUri: 'https://example.com/mock-images/thumbs/presc4.png',
    notes: 'Allergy ointment recommended',
    uploadedBy: 'user',
    status: 'processed',
    createdAt: '2025-10-01T07:45:00.000Z',
    reminderDate: '2025-11-12T14:00:00.000Z',
  },
  {
    id: 'presc_005',
    patientName: 'Vikram Rana',
    type: 'pdf',
    fileName: 'xray_report.pdf',
    fileUri: 'https://example.com/mock-pdfs/presc5.pdf',
    thumbnailUri: 'https://example.com/mock-images/thumbs/pdf-placeholder.png',
    notes: 'Follow up in 2 weeks',
    uploadedBy: 'hospital',
    status: 'completed',
    createdAt: '2025-09-15T11:20:00.000Z',
    reminderDate: '2025-11-20T11:00:00.000Z',
  },
  {
    id: 'presc_006',
    patientName: 'Anjali Mehta',
    type: 'link',
    fileName: 'lab-results',
    fileUri: 'https://labs.example.com/results/abc123',
    thumbnailUri: 'https://example.com/mock-images/thumbs/link-placeholder.png',
    notes: 'View complete report on external lab portal',
    uploadedBy: 'lab',
    status: 'completed',
    createdAt: '2025-10-21T10:05:00.000Z',
    reminderDate: '2025-11-03T09:00:00.000Z',
  },
  {
    id: 'presc_007',
    patientName: 'Ramesh Kumar',
    type: 'image',
    fileName: 'presc_handwritten.jpg',
    fileUri: 'https://example.com/mock-images/presc7.jpg',
    thumbnailUri: 'https://example.com/mock-images/thumbs/presc7.jpg',
    notes: 'Handwritten Rx, needs pharmacist verification',
    uploadedBy: 'user',
    status: 'completed',
    createdAt: '2025-10-25T13:50:00.000Z',
    reminderDate: '2025-11-02T15:00:00.000Z',
  },
  {
    id: 'presc_008',
    patientName: 'Geeta Singh',
    type: 'pdf',
    fileName: 'diabetes-monitoring.pdf',
    fileUri: 'https://example.com/mock-pdfs/presc8.pdf',
    thumbnailUri: 'https://example.com/mock-images/thumbs/pdf-placeholder.png',
    notes: 'HbA1c report — diet plan updated',
    uploadedBy: 'clinic',
    status: 'missed',
    createdAt: '2025-09-05T08:10:00.000Z',
    reminderDate: '2025-11-30T08:30:00.000Z',
  },
  {
    id: 'presc_009',
    patientName: 'Karan Patel',
    type: 'link',
    fileName: 'video-consult-record',
    fileUri: 'https://videos.example.com/records/vid987',
    thumbnailUri:
      'https://example.com/mock-images/thumbs/video-placeholder.png',
    notes: 'Consultation recording and Rx in description',
    uploadedBy: 'doctor',
    status: 'pending',
    createdAt: '2025-10-11T19:40:00.000Z',
    reminderDate: '2025-11-08T18:00:00.000Z',
  },
  {
    id: 'presc_010',
    patientName: 'Meera Nair',
    type: 'image',
    fileName: 'eye_report.jpg',
    fileUri: 'https://example.com/mock-images/presc10.jpg',
    thumbnailUri: 'https://example.com/mock-images/thumbs/presc10.jpg',
    notes: 'Optometrist prescription for lenses',
    uploadedBy: 'user',
    status: 'processed',
    createdAt: '2025-10-30T09:00:00.000Z',
    reminderDate: '2025-11-25T09:00:00.000Z',
  },
];

export default mockPrescriptions;
